// <auto-generated />
using System;
using DATNSD54.DAO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATNSD54.DAO.Migrations
{
    [DbContext(typeof(DbContextApp))]
    [Migration("20260328125147_12343214324")]
    partial class _12343214324
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATNSD54.DAO.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiChitiet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChiChitiet = "Số 123, Đường Trịnh Văn Bô, Phương Canh, Nam Từ Liêm, Hà Nội",
                            HoTen = "Nguyễn Văn Admin",
                            IdCustomer = 1,
                            SDT = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            DiaChiChitiet = "Tòa nhà FPT Poly, Cầu Giấy, Hà Nội",
                            HoTen = "Văn Admin (Cơ quan)",
                            IdCustomer = 1,
                            SDT = "0243123456"
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Bill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("Address_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia_Goc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Phuong_Thuc_Thanh_Toan")
                        .HasColumnType("int");

                    b.Property<decimal>("Thanh_Tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trang_Thai")
                        .HasColumnType("int");

                    b.Property<int?>("User_ID")
                        .HasColumnType("int");

                    b.Property<string>("VoucherShip_ID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Voucher_ID")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("AddressId");

                    b.HasIndex("Address_Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("User_ID");

                    b.HasIndex("VoucherShip_ID");

                    b.HasIndex("Voucher_ID");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.BillItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Bill_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Don_Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gia_Ban")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ProductDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Product_Detail_ID")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Bill_ID");

                    b.HasIndex("ProductDetailId");

                    b.ToTable("BillItem");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "logo.png",
                            Ten = "FourStars Shoes",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Trang_Thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Customer_ID");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Customer_ID = 1,
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(4029),
                            Trang_Thai = 1
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cart_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_Detail_ID")
                        .HasColumnType("int");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.Property<bool>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("Cart_ID");

                    b.HasIndex("Product_Detail_ID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ma = "#000000",
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3817),
                            Ten = "Đen"
                        },
                        new
                        {
                            Id = 2,
                            Ma = "#FFFFFF",
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3819),
                            Ten = "Trắng"
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gioi_Tinh")
                        .HasColumnType("bit");

                    b.Property<string>("Mat_Khau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Ngay_Sinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@fourstars.com",
                            Gioi_Tinh = true,
                            Mat_Khau = "$2a$11$KiUJ/sCWTSqMSRKPkddVOOm96dqF54Dk50YiIYghacO7P9BZlQkDC",
                            Ngay_Sinh = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3981),
                            SDT = "0912345678",
                            Ten = "Nguyễn Văn Admin",
                            Trang_Thai = true
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("IMG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("Product_ID");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IMG = "~/img/product/ambush1.jpg",
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(4052),
                            Product_ID = 1,
                            Trang_Thai = true
                        },
                        new
                        {
                            ID = 2,
                            IMG = "~/img/product/addidas1.jpg",
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(4054),
                            Product_ID = 1,
                            Trang_Thai = true
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Brand_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mo_Ta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nam_SX")
                        .HasColumnType("int");

                    b.Property<int>("Product_Type_ID")
                        .HasColumnType("int");

                    b.Property<int>("Supplier_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Brand_ID");

                    b.HasIndex("Product_Type_ID");

                    b.HasIndex("Supplier_ID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand_ID = 1,
                            Ma = "PROD001",
                            Mo_Ta = "Mẫu giày bán chạy nhất 2026",
                            Nam_SX = 2026,
                            Product_Type_ID = 1,
                            Supplier_ID = 1,
                            Ten = "Giày Unisex FourStars Classic"
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<decimal>("Don_Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("SL")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Color");

                    b.HasIndex("Product_ID");

                    b.HasIndex("Size");

                    b.ToTable("ProductDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = 1,
                            Don_Gia = 500000m,
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3957),
                            Product_ID = 1,
                            SL = 100,
                            Sale = 0,
                            Size = 1,
                            Trang_Thai = true
                        },
                        new
                        {
                            Id = 2,
                            Color = 2,
                            Don_Gia = 550000m,
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3960),
                            Product_ID = 1,
                            SL = 50,
                            Sale = 5,
                            Size = 2,
                            Trang_Thai = true
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ma = "SNK",
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3791),
                            Ten = "Giày Sneaker",
                            Trang_Thai = true
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ma = 37,
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3902),
                            Ten = "37"
                        },
                        new
                        {
                            Id = 2,
                            Ma = 38,
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3903),
                            Ten = "38"
                        },
                        new
                        {
                            Id = 3,
                            Ma = 39,
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3905),
                            Ten = "39"
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dia_Chi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dia_Chi = "Hà Nội",
                            Email = "khohn@gmail.com",
                            Ngay_Tao = new DateTime(2026, 3, 28, 19, 51, 46, 775, DateTimeKind.Local).AddTicks(3570),
                            SDT = "0987654321",
                            Ten = "Tổng kho Unisex HN",
                            Trang_Thai = true
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Anhdaidien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia_Chi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gioi_Tinh")
                        .HasColumnType("bit");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mat_Khau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Ngay_Sinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Role")
                        .HasColumnType("bit");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Trang_Thai")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Anhdaidien = "noavatar.png",
                            CCCD = "012345678901",
                            Dia_Chi = "Hà Nội, Việt Nam",
                            Email = "admin@fourstars.com",
                            Gioi_Tinh = true,
                            Ma = "ADMIN001",
                            Mat_Khau = "$2a$11$KiUJ/sCWTSqMSRKPkddVOOm96dqF54Dk50YiIYghacO7P9BZlQkDC",
                            Ngay_Sinh = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ngay_Tao = new DateTime(2024, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = true,
                            SDT = "0912345678",
                            Ten = "Quản Trị Viên Hệ Thống",
                            Trang_Thai = true
                        },
                        new
                        {
                            ID = 2,
                            Anhdaidien = "noavatar.png",
                            CCCD = "012345678902",
                            Dia_Chi = "Hải Phòng, Việt Nam",
                            Email = "nhanvien1@gmail.com",
                            Gioi_Tinh = false,
                            Ma = "NV001",
                            Mat_Khau = "$2a$11$KiUJ/sCWTSqMSRKPkddVOOm96dqF54Dk50YiIYghacO7P9BZlQkDC",
                            Ngay_Sinh = new DateTime(2002, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ngay_Tao = new DateTime(2024, 1, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = false,
                            SDT = "0334567890",
                            Ten = "Nguyễn Nhân Viên",
                            Trang_Thai = true
                        });
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Voucher", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Don_Hang_Toi_Thieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Giam_Toi_Da")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Ngay_Bat_Dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Ket_Thuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Trang_Thai")
                        .HasColumnType("int");

                    b.Property<decimal>("Ty_Le_Giam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Vourcher");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.VoucherShip", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Don_Hang_Toi_Thieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Ngay_Bat_Dau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Ket_Thuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("So_Luong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Trang_Thai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("VoucherShip");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Address", b =>
                {
                    b.HasOne("DATNSD54.DAO.Models.Customer", "Customer")
                        .WithMany("Address")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Bill", b =>
                {
                    b.HasOne("DATNSD54.DAO.Models.Address", null)
                        .WithMany("Bills")
                        .HasForeignKey("AddressId");

                    b.HasOne("DATNSD54.DAO.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("Address_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DATNSD54.DAO.Models.Customer", null)
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId");

                    b.HasOne("DATNSD54.DAO.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DATNSD54.DAO.Models.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("User_ID");

                    b.HasOne("DATNSD54.DAO.Models.VoucherShip", "VoucherShip")
                        .WithMany("Bills")
                        .HasForeignKey("VoucherShip_ID");

                    b.HasOne("DATNSD54.DAO.Models.Voucher", "Voucher")
                        .WithMany("Bills")
                        .HasForeignKey("Voucher_ID");

                    b.Navigation("Address");

                    b.Navigation("Customer");

                    b.Navigation("User");

                    b.Navigation("Voucher");

                    b.Navigation("VoucherShip");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.BillItem", b =>
                {
                    b.HasOne("DATNSD54.DAO.Models.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("Bill_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNSD54.DAO.Models.ProductDetail", null)
                        .WithMany("BillItems")
                        .HasForeignKey("ProductDetailId");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Cart", b =>
                {
                    b.HasOne("DATNSD54.DAO.Models.Customer", null)
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId");

                    b.HasOne("DATNSD54.DAO.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.CartItem", b =>
                {
                    b.HasOne("DATNSD54.DAO.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("Cart_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNSD54.DAO.Models.ProductDetail", "ProductDetail")
                        .WithMany("CartItems")
                        .HasForeignKey("Product_Detail_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Image", b =>
                {
                    b.HasOne("DATNSD54.DAO.Models.Product", "Product")
                        .WithMany("images")
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Product", b =>
                {
                    b.HasOne("DATNSD54.DAO.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("Brand_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNSD54.DAO.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("Product_Type_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNSD54.DAO.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("Supplier_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("ProductType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.ProductDetail", b =>
                {
                    b.HasOne("DATNSD54.DAO.Models.Color", "ColorNavigation")
                        .WithMany("ProductDetails")
                        .HasForeignKey("Color")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNSD54.DAO.Models.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNSD54.DAO.Models.Size", "SizeNavigation")
                        .WithMany("ProductDetails")
                        .HasForeignKey("Size")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorNavigation");

                    b.Navigation("Product");

                    b.Navigation("SizeNavigation");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Address", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Bill", b =>
                {
                    b.Navigation("BillItems");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Color", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Customer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Bills");

                    b.Navigation("Carts");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Product", b =>
                {
                    b.Navigation("ProductDetails");

                    b.Navigation("images");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.ProductDetail", b =>
                {
                    b.Navigation("BillItems");

                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Size", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.User", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.Voucher", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("DATNSD54.DAO.Models.VoucherShip", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
